name: Deploy

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      name: Create GitHub Release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
